[[language]]
name = "rust"
auto-format = false
[[language]]
name = "python"

[[language]]
name = "c"

[[language]]
name = "cpp"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false


[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true
